### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by alexcom** [AlexNk/intelite_smt006_remote#1]
Hi, man. Don't know how to ping you in another way so opening an issue.
I'm looking for a way to control my 3 lamps via Home Assistant + MQTT.
Probably I'll have to port your code to Go. Before I dive deeper would be nice to know for sure.
So my questions:
1. Does this thing work?
2. Where did you get info about message format?

**Comment by AlexNk** [comment]
Hi

It does work for my lamp SMT006 and I was told it works also for at least SMT005. It may also work for other models but I don't have a way to test it. Since it was created for 006, it may work only partially on the other lamps with different functions.

I reversed the message format and control sum using LIRC and IR receiver.

**Comment by alexcom** [comment]
Cool! Thanks for swift response!

**Comment by alexcom** [comment]
FYI I've implemented basic service for my needs. It's here: https://github.com/alexcom/intelite-mqtt. Main on/of,brightness,color,night mode, max mode all work without issues. I did not test the rest except one attempt to turn lamp on on timer which did not work for some reason. Maybe it's my buggy port or maybe it's SMT005 vs SMT006 issue. Doesn't matter much for me. Thanks again for relieving me from analyzing IR protocol by myself 🥇 👍 .
